 local menu98edb85b00d9527ad5acebe451b3fae6 = {
     {"Android File Transfer (MTP)", "android-file-transfer", "/usr/share//icons/hicolor/128x128/apps/android-file-transfer.png" },
     {"Ark", "ark ", "/usr/share//icons/hicolor/48x48/apps/ark.png" },
     {"Disks", "gnome-disks", "/usr/share//icons/hicolor/16x16/apps/gnome-disks.png" },
     {"Filelight", "filelight ", "/usr/share//icons/hicolor/16x16/apps/filelight.png" },
     {"GTKWave", "gtkwave", "/usr/share//icons/gnome/16x16/mimetypes/gtkwave.png" },
     {"GVim", "gvim -f ", "/usr/share//icons/hicolor/48x48/apps/gvim.png" },
     {"Gnote", "gnote ", "/usr/share//icons/hicolor/16x16/apps/gnote.png" },
     {"Jupyter Qt console", "jupyter qtconsole", "///usr/lib/python3.6/site-packages/qtconsole/resources/icon/JupyterConsole.svg" },
     {"KAlarm", "kalarm", "/usr/share//icons/hicolor/16x16/apps/kalarm.png" },
     {"KCharSelect", "kcharselect --qwindowtitle KCharSelect", "/usr/share//icons/gnome/16x16/apps/accessories-character-map.png" },
     {"KMail Import Wizard", "importwizard", "/usr/share//icons/hicolor/64x64/apps/kontact-import-wizard.png" },
     {"KNotes", "knotes", "/usr/share//icons/hicolor/16x16/apps/knotes.png" },
     {"KWrite", "kwrite ", "/usr/share//icons/hicolor/16x16/apps/kwrite.png" },
     {"Kate", "kate -b ", "/usr/share//icons/hicolor/16x16/apps/kate.png" },
     {"Kleopatra", "kleopatra", "/usr/share//icons/hicolor/16x16/apps/kleopatra.png" },
     {"Klipper", "klipper"},
     {"Redshift", "redshift-gtk"},
     {"Screenshot", "gnome-screenshot --interactive", "/usr/share//icons/gnome/16x16/apps/applets-screenshooter.png" },
     {"Spectacle", "spectacle", "/usr/share//icons/hicolor/16x16/apps/spectacle.png" },
     {"Tomboy Notes", "tomboy --search", "/usr/share//icons/hicolor/16x16/apps/tomboy.png" },
     {"Xournal", "xournal "},
     {"compton", "compton --xrender-sync-fence", "/usr/share//icons/hicolor/48x48/apps/compton.png" },
     {"ipython", "xterm -e ipython", "/usr/share/pixmaps/ipython.png" },
 }

 local menude7a22a0c94aa64ba2449e520aa20c99 = {
     {"Artikulate", "artikulate -caption Artikulate ", "/usr/share//icons/hicolor/16x16/apps/artikulate.png" },
     {"GNU Octave", "/usr/bin/octave --force-gui ", "/usr/share//icons/hicolor/16x16/apps/octave.png" },
     {"LibreOffice Math", "libreoffice --math ", "/usr/share//icons/hicolor/16x16/apps/libreoffice-math.png" },
     {"Mendeley Desktop", "mendeleydesktop ", "/usr/share//icons/hicolor/16x16/apps/mendeleydesktop.png" },
     {"Mendeley Desktop", "/home/jagan/.local/share/mendeleydesktop ", "/usr/share//icons/hicolor/16x16/apps/mendeleydesktop.png" },
 }

 local menu251bd8143891238ecedc306508e29017 = {
     {"Armagetron Advanced", "armagetronad", "/usr/share/pixmaps/armagetronad.png" },
     {"Astromenace", "astromenace", "///usr/share/pixmaps/astromenace.png" },
     {"Dosbox", "dosbox", "/usr/share/pixmaps/dosbox.png" },
     {"Mari0", "mari0"},
     {"SuperTux 2", "supertux2", "/usr/share/pixmaps/supertux.png" },
     {"Xboard", "xboard", "/usr/share//icons/hicolor/48x48/apps/xboard.png" },
 }

 local menud334dfcea59127bedfcdbe0a3ee7f494 = {
     {"Dia Diagram Editor", "dia ", "/usr/share//icons/hicolor/16x16/apps/dia.png" },
     {"Document Viewer", "evince ", "/usr/share//icons/hicolor/16x16/apps/evince.png" },
     {"FontForge", "fontforge ", "/usr/share//icons/hicolor/16x16/apps/fontforge.png" },
     {"GNU Image Manipulation Program", "gimp-2.8 ", "/usr/share//icons/hicolor/16x16/apps/gimp.png" },
     {"Inkscape", "inkscape ", "/usr/share//icons/hicolor/16x16/apps/inkscape.png" },
     {"LibreOffice Draw", "libreoffice --draw ", "/usr/share//icons/hicolor/16x16/apps/libreoffice-draw.png" },
     {"Okular", "okular ", "/usr/share//icons/hicolor/16x16/apps/okular.png" },
     {"PhotoQt", "photoqt ", "/usr/share//icons/hicolor/16x16/apps/photoqt.png" },
     {"Rapid Photo Downloader", "rapid-photo-downloader", "/usr/share//icons/hicolor/16x16/apps/rapid-photo-downloader.png" },
     {"XSane - Scanning", "xsane", "/usr/share/pixmaps/xsane.xpm" },
 }

 local menuc8205c7636e728d448c2774e6a4a944b = {
     {"Akregator", "akregator ", "/usr/share//icons/hicolor/16x16/apps/akregator.png" },
     {"Avahi SSH Server Browser", "/usr/bin/bssh", "/usr/share//icons/gnome/16x16/devices/network-wired.png" },
     {"Avahi VNC Server Browser", "/usr/bin/bvnc", "/usr/share//icons/gnome/16x16/devices/network-wired.png" },
     {"Blogilo", "blogilo", "/usr/share//icons/hicolor/16x16/apps/blogilo.png" },
     {"Cloud Storage Manager", "storageservicemanager", "/usr/share//icons/hicolor/16x16/apps/kmail.png" },
     {"Contact Print Theme Editor", "contactprintthemeeditor", "/usr/share//icons/hicolor/16x16/apps/kaddressbook.png" },
     {"Contact Theme Editor", "contactthemeeditor", "/usr/share//icons/hicolor/16x16/apps/kaddressbook.png" },
     {"Corebird", "corebird", "/usr/share//icons/hicolor/16x16/apps/corebird.png" },
     {"Dropbox", "dropbox", "/usr/share/pixmaps/dropbox.png" },
     {"ELinks", "xterm -e /usr/bin/elinks ", "/usr/share//icons/gnome/16x16/mimetypes/html.png" },
     {"Firefox", "firefox ", "/usr/share//icons/hicolor/16x16/apps/firefox.png" },
     {"Google Chrome", "/usr/bin/google-chrome-stable ", "/usr/share//icons/hicolor/16x16/apps/google-chrome.png" },
     {"Gradio", "gradio", "/usr/share//icons/hicolor/16x16/apps/de.haeckerfelix.gradio.png" },
     {"KDE Connect Monitor", "plasmawindowed org.kde.kdeconnect --statusnotifier", "/usr/share//icons/hicolor/16x16/apps/kdeconnect.png" },
     {"KMail", "kmail -qwindowtitle KMail ", "/usr/share//icons/hicolor/16x16/apps/kmail.png" },
     {"KMail Header Theme Editor", "headerthemeeditor", "/usr/share//icons/hicolor/16x16/apps/kmail.png" },
     {"KTnef", "ktnef ", "/usr/share//icons/hicolor/48x48/apps/ktnef.png" },
     {"Konqueror", "konqueror", "/usr/share//icons/hicolor/16x16/apps/konqueror.png" },
     {"Mumble", "mumble "},
     {"PIM Setting Exporter", "pimsettingexporter", "/usr/share//icons/hicolor/16x16/apps/kontact.png" },
     {"QupZilla", "qupzilla ", "/usr/share//icons/hicolor/16x16/apps/qupzilla.png" },
     {"Ricochet IM", "ricochet", "/usr/share//icons/hicolor/48x48/apps/ricochet.png" },
     {"Sieve Editor", "sieveeditor", "/usr/share//icons/hicolor/16x16/apps/kmail.png" },
     {"Skype for Linux Beta", "/usr/bin/skypeforlinux ", "/usr/share//icons/hicolor/16x16/apps/skypeforlinux.png" },
     {"Transmission", "transmission-gtk ", "/usr/share//icons/hicolor/16x16/apps/transmission.png" },
     {"Wire", "\"/opt/Wire/wire\"", "/usr/share//icons/hicolor/32x32/apps/wire.png" },
     {"Wireshark (GTK+)", "wireshark-gtk ", "/usr/share//icons/hicolor/16x16/apps/wireshark.png" },
     {"qTox", "qtox ", "/usr/share//icons/hicolor/16x16/apps/qtox.png" },
     {"qutebrowser", "qutebrowser ", "/usr/share//icons/hicolor/16x16/apps/qutebrowser.png" },
 }

 local menudf814135652a5a308fea15bff37ea284 = {
     {"Cloud Storage Manager", "storageservicemanager", "/usr/share//icons/hicolor/16x16/apps/kmail.png" },
     {"Contact Print Theme Editor", "contactprintthemeeditor", "/usr/share//icons/hicolor/16x16/apps/kaddressbook.png" },
     {"Contact Theme Editor", "contactthemeeditor", "/usr/share//icons/hicolor/16x16/apps/kaddressbook.png" },
     {"Document Viewer", "evince ", "/usr/share//icons/hicolor/16x16/apps/evince.png" },
     {"KAddressBook", "kaddressbook ", "/usr/share//icons/hicolor/16x16/apps/kaddressbook.png" },
     {"KMail", "kmail -qwindowtitle KMail ", "/usr/share//icons/hicolor/16x16/apps/kmail.png" },
     {"KMail Header Theme Editor", "headerthemeeditor", "/usr/share//icons/hicolor/16x16/apps/kmail.png" },
     {"KOrganizer", "korganizer ", "/usr/share//icons/hicolor/16x16/apps/korganizer.png" },
     {"KTnef", "ktnef ", "/usr/share//icons/hicolor/48x48/apps/ktnef.png" },
     {"Kontact", "kontact", "/usr/share//icons/hicolor/16x16/apps/kontact.png" },
     {"LibreOffice", "libreoffice ", "/usr/share//icons/hicolor/16x16/apps/libreoffice-startcenter.png" },
     {"LibreOffice Base", "libreoffice --base ", "/usr/share//icons/hicolor/16x16/apps/libreoffice-base.png" },
     {"LibreOffice Calc", "libreoffice --calc ", "/usr/share//icons/hicolor/16x16/apps/libreoffice-calc.png" },
     {"LibreOffice Draw", "libreoffice --draw ", "/usr/share//icons/hicolor/16x16/apps/libreoffice-draw.png" },
     {"LibreOffice Impress", "libreoffice --impress ", "/usr/share//icons/hicolor/16x16/apps/libreoffice-impress.png" },
     {"LibreOffice Math", "libreoffice --math ", "/usr/share//icons/hicolor/16x16/apps/libreoffice-math.png" },
     {"LibreOffice Writer", "libreoffice --writer ", "/usr/share//icons/hicolor/16x16/apps/libreoffice-writer.png" },
     {"Okular", "okular ", "/usr/share//icons/hicolor/16x16/apps/okular.png" },
     {"PIM Setting Exporter", "pimsettingexporter", "/usr/share//icons/hicolor/16x16/apps/kontact.png" },
     {"Sieve Editor", "sieveeditor", "/usr/share//icons/hicolor/16x16/apps/kmail.png" },
     {"TeXstudio", "texstudio "},
     {"WordNet", "wnb", "///usr/share/pixmaps/wordnet.png" },
     {"Zathura", "zathura "},
     {"Zotero", "/usr/bin/zotero ", "/usr/share//icons/hicolor/16x16/apps/zotero.png" },
 }

 local menu6311ae17c1ee52b36e68aaf4ad066387 = {
     {"Xcircuit", "xcircuit", "/usr/share//icons/xcircuit.png" },
 }

 local menue6f43c40ab1c07cd29e4e83e4ef6bf85 = {
     {"Akonadi Console", "akonadiconsole", "/usr/share//icons/hicolor/16x16/apps/akonadiconsole.png" },
     {"CMake", "cmake-gui ", "/usr/share//icons/hicolor/32x32/apps/CMakeSetup.png" },
     {"Cuttlefish", "cuttlefish"},
     {"D-Feet", "d-feet", "/usr/share//icons/hicolor/16x16/apps/d-feet.png" },
     {"Data Display Debugger", "ddd", "/usr/share/pixmaps/ddd.xpm" },
     {"FLUID", "fluid ", "/usr/share//icons/hicolor/16x16/apps/fluid.png" },
     {"GRC", "gnuradio-companion "},
     {"Julia", "xterm -e julia"},
     {"Jupyter Qt console", "jupyter qtconsole", "///usr/lib/python3.6/site-packages/qtconsole/resources/icon/JupyterConsole.svg" },
     {"OpenJDK 1.7.0 Policy Tool", "_BINDIR_/policytool"},
     {"Plasma Look And Feel Explorer", "lookandfeelexplorer", "/usr/share//icons/gnome/16x16/apps/preferences-desktop-theme.png" },
     {"Plasma Theme Explorer", "plasmathemeexplorer", "/usr/share//icons/gnome/16x16/apps/preferences-desktop-theme.png" },
     {"Plasmate", "plasmate"},
     {"Qt Assistant", "assistant", "/usr/share//icons/hicolor/32x32/apps/assistant.png" },
     {"Qt Creator", "qtcreator ", "/usr/share//icons/hicolor/16x16/apps/QtProject-qtcreator.png" },
     {"Qt Designer", "designer", "/usr/share//icons/hicolor/128x128/apps/QtProject-designer.png" },
     {"Qt Linguist", "linguist", "/usr/share//icons/hicolor/16x16/apps/linguist.png" },
     {"Qt QDbusViewer ", "qdbusviewer", "/usr/share//icons/hicolor/32x32/apps/qdbusviewer.png" },
     {"Qt4 Assistant ", "assistant-qt4", "/usr/share//icons/hicolor/32x32/apps/assistant-qt4.png" },
     {"Qt4 Designer", "designer-qt4", "/usr/share//icons/hicolor/128x128/apps/designer-qt4.png" },
     {"Qt4 Linguist ", "linguist-qt4", "/usr/share//icons/hicolor/16x16/apps/linguist-qt4.png" },
     {"Qt4 QDbusViewer ", "qdbusviewer-qt4", "/usr/share//icons/hicolor/32x32/apps/qdbusviewer-qt4.png" },
     {"ipython", "xterm -e ipython", "/usr/share/pixmaps/ipython.png" },
 }

 local menu80d754c83abbbd4ef5d150904efcc86c = {
     {"Julia", "xterm -e julia"},
 }

 local menu52dd1c847264a75f400961bfb4d1c849 = {
     {"Audacity", "env UBUNTU_MENUPROXY=0 audacity ", "/usr/share//icons/hicolor/16x16/apps/audacity.png" },
     {"Cheese", "cheese", "/usr/share//icons/hicolor/16x16/apps/org.gnome.Cheese.png" },
     {"Clementine", "clementine ", "/usr/share//icons/hicolor/64x64/apps/clementine.png" },
     {"FFADO Mixer", "ffado-mixer", "/usr/share/pixmaps/ffado.png" },
     {"Kdenlive", "kdenlive ", "/usr/share//icons/hicolor/16x16/apps/kdenlive.png" },
     {"PulseAudio Volume Control", "pavucontrol", "/usr/share//icons/hicolor/16x16/apps/multimedia-volume-control.png" },
     {"Qt V4L2 test Utility", "qv4l2", "/usr/share//icons/hicolor/16x16/apps/qv4l2.png" },
     {"Spotify", "spotify ", "/usr/share/pixmaps/spotify-client.png" },
     {"guvcview", "guvcview", "///usr/share/pixmaps/guvcview/guvcview.png" },
     {"mpv Media Player", "mpv --player-operation-mode=pseudo-gui -- ", "/usr/share//icons/hicolor/16x16/apps/mpv.png" },
     {"qTox", "qtox ", "/usr/share//icons/hicolor/16x16/apps/qtox.png" },
 }

 local menuee69799670a33f75d45c57d1d1cd0ab3 = {
     {"Avahi Zeroconf Browser", "/usr/bin/avahi-discover", "/usr/share//icons/gnome/16x16/devices/network-wired.png" },
     {"Boxes", "gnome-boxes ", "/usr/share//icons/hicolor/16x16/apps/gnome-boxes.png" },
     {"Color Profile Viewer", "gcm-viewer", "/usr/share//icons/hicolor/16x16/apps/gnome-color-manager.png" },
     {"Configuration Editor", "gconf-editor", "/usr/share//icons/hicolor/16x16/apps/gconf-editor.png" },
     {"Disk Usage Analyzer", "baobab", "/usr/share//icons/hicolor/16x16/apps/baobab.png" },
     {"Dolphin", "dolphin ", "/usr/share//icons/gnome/16x16/apps/system-file-manager.png" },
     {"FSV", "fsv2", "/usr/share/pixmaps/fsv2.xpm" },
     {"GParted", "/usr/bin/gparted_polkit ", "/usr/share//icons/hicolor/16x16/apps/gparted.png" },
     {"Hardware Locality lstopo", "lstopo"},
     {"Htop", "xterm -e htop", "/usr/share/pixmaps/htop.png" },
     {"IBus (KIMPanel)", "ibus-daemon --panel=/usr/lib/kimpanel-ibus-panel"},
     {"KSysGuard", "ksysguard ", "/usr/share//icons/gnome/16x16/apps/utilities-system-monitor.png" },
     {"KWalletManager", "kwalletmanager5 ", "/usr/share//icons/hicolor/16x16/apps/kwalletmanager.png" },
     {"Konsole", "konsole", "/usr/share//icons/gnome/16x16/apps/utilities-terminal.png" },
     {"LSHW", "/usr/sbin/gtk-lshw", "///usr/share/lshw/artwork/logo.svg" },
     {"Manage Printing", "/usr/bin/xdg-open http://localhost:631/", "/usr/share//icons/hicolor/16x16/apps/cups.png" },
     {"Multilingual terminal (mlclient)", "mlclient", "/usr/share/pixmaps/mlclient.png" },
     {"Multilingual terminal (mlterm)", "mlterm", "/usr/share/pixmaps/mlterm.png" },
     {"Pacman Log Viewer", "plv", "/usr/share//icons/hicolor/16x16/apps/plv.png" },
     {"Psensor", "psensor", "/usr/share//icons/hicolor/16x16/apps/psensor.png" },
     {"UXTerm", "uxterm", "/usr/share/pixmaps/xterm-color_48x48.xpm" },
     {"Vifm", "xterm -e vifm ", "/usr/share/pixmaps/vifm.png" },
     {"Virtual Machine Manager", "virt-manager", "/usr/share//icons/hicolor/16x16/apps/virt-manager.png" },
     {"XTerm", "xterm", "/usr/share/pixmaps/xterm-color_48x48.xpm" },
     {"dconf Editor", "dconf-editor", "/usr/share//icons/hicolor/16x16/apps/dconf-editor.png" },
     {"gtk2fontsel", "gtk2fontsel"},
     {"ranger", "xterm -e ranger", "/usr/share//icons/gnome/16x16/apps/utilities-terminal.png" },
     {"st", "st", "/usr/share//icons/gnome/16x16/apps/utilities-terminal.png" },
     {"urxvt", "urxvt", "/usr/share//icons/gnome/16x16/apps/utilities-terminal.png" },
     {"urxvt (client)", "urxvtc", "/usr/share//icons/gnome/16x16/apps/utilities-terminal.png" },
     {"urxvt (tabbed)", "urxvt-tabbed", "/usr/share//icons/gnome/16x16/apps/utilities-terminal.png" },
 }

xdgmenu = {
    {"Accessories", menu98edb85b00d9527ad5acebe451b3fae6},
    {"Education", menude7a22a0c94aa64ba2449e520aa20c99},
    {"Games", menu251bd8143891238ecedc306508e29017},
    {"Graphics", menud334dfcea59127bedfcdbe0a3ee7f494},
    {"Internet", menuc8205c7636e728d448c2774e6a4a944b},
    {"Office", menudf814135652a5a308fea15bff37ea284},
    {"Other", menu6311ae17c1ee52b36e68aaf4ad066387},
    {"Programming", menue6f43c40ab1c07cd29e4e83e4ef6bf85},
    {"Science & Math", menu80d754c83abbbd4ef5d150904efcc86c},
    {"Sound & Video", menu52dd1c847264a75f400961bfb4d1c849},
    {"System Tools", menuee69799670a33f75d45c57d1d1cd0ab3},
}

