 local menu98edb85b00d9527ad5acebe451b3fae6 = {
     {"Android File Transfer (MTP)", "android-file-transfer", "/usr/share//icons/hicolor/128x128/apps/android-file-transfer.png" },
     {"Archive Manager", "file-roller ", "/usr/share//icons/hicolor/16x16/apps/file-roller.png" },
     {"Clocks", "gnome-clocks", "/usr/share//icons/hicolor/16x16/apps/org.gnome.clocks.png" },
     {"Desktop Search", "tracker-needle", "/usr/share//icons/gnome/16x16/actions/system-search.png" },
     {"Disks", "gnome-disks", "/usr/share//icons/hicolor/16x16/apps/gnome-disks.png" },
     {"Filelight", "filelight ", "/usr/share//icons/hicolor/16x16/apps/filelight.png" },
     {"Files", "nautilus --new-window ", "/usr/share//icons/hicolor/16x16/apps/org.gnome.Nautilus.png" },
     {"GTKWave", "gtkwave", "/usr/share//icons/gnome/16x16/mimetypes/gtkwave.png" },
     {"GVim", "gvim -f ", "/usr/share//icons/hicolor/48x48/apps/gvim.png" },
     {"Gnote", "gnote ", "/usr/share//icons/hicolor/16x16/apps/gnote.png" },
     {"Klipper", "klipper"},
     {"Maps", "gapplication launch org.gnome.Maps", "/usr/share//icons/hicolor/16x16/apps/org.gnome.Maps.png" },
     {"Redshift", "redshift-gtk"},
     {"Screenshot", "gnome-screenshot --interactive", "/usr/share//icons/gnome/16x16/apps/applets-screenshooter.png" },
     {"Spectacle", "spectacle", "/usr/share//icons/hicolor/16x16/apps/spectacle.png" },
     {"Tomboy Notes", "tomboy --search", "/usr/share//icons/hicolor/16x16/apps/tomboy.png" },
     {"Weather", "gapplication launch org.gnome.Weather.Application", "/usr/share//icons/hicolor/16x16/apps/org.gnome.Weather.png" },
     {"compton", "compton --xrender-sync-fence", "/usr/share//icons/hicolor/48x48/apps/compton.png" },
     {"ipython", "xterm -e ipython", "/usr/share/pixmaps/ipython.png" },
 }

 local menude7a22a0c94aa64ba2449e520aa20c99 = {
     {"Artikulate", "artikulate -caption Artikulate ", "/usr/share//icons/hicolor/16x16/apps/artikulate.png" },
     {"GNU Octave", "/usr/bin/octave --force-gui ", "/usr/share//icons/hicolor/16x16/apps/octave.png" },
     {"LibreOffice Math", "libreoffice --math ", "/usr/share//icons/hicolor/16x16/apps/libreoffice-math.png" },
     {"Mendeley Desktop", "mendeleydesktop ", "/usr/share//icons/hicolor/16x16/apps/mendeleydesktop.png" },
     {"Mendeley Desktop", "/home/jagan/.local/share/mendeleydesktop ", "/usr/share//icons/hicolor/16x16/apps/mendeleydesktop.png" },
 }

 local menu251bd8143891238ecedc306508e29017 = {
     {"Astromenace", "astromenace", "///usr/share/pixmaps/astromenace.png" },
     {"Chess", "gnome-chess", "/usr/share//icons/hicolor/16x16/apps/gnome-chess.png" },
     {"Dosbox", "dosbox", "/usr/share/pixmaps/dosbox.png" },
     {"Mari0", "mari0"},
     {"SuperTux 2", "supertux2", "/usr/share/pixmaps/supertux.png" },
     {"Xboard", "xboard", "/usr/share//icons/hicolor/48x48/apps/xboard.png" },
 }

 local menud334dfcea59127bedfcdbe0a3ee7f494 = {
     {"Dia Diagram Editor", "dia ", "/usr/share//icons/hicolor/16x16/apps/dia.png" },
     {"Document Viewer", "evince ", "/usr/share//icons/hicolor/16x16/apps/evince.png" },
     {"FontForge", "fontforge ", "/usr/share//icons/hicolor/16x16/apps/fontforge.png" },
     {"GNU Image Manipulation Program", "gimp-2.8 ", "/usr/share//icons/hicolor/16x16/apps/gimp.png" },
     {"Image Viewer", "eog ", "/usr/share//icons/hicolor/16x16/apps/eog.png" },
     {"Inkscape", "inkscape ", "/usr/share//icons/hicolor/16x16/apps/inkscape.png" },
     {"LibreOffice Draw", "libreoffice --draw ", "/usr/share//icons/hicolor/16x16/apps/libreoffice-draw.png" },
     {"Okular", "okular ", "/usr/share//icons/hicolor/16x16/apps/okular.png" },
     {"Rapid Photo Downloader", "rapid-photo-downloader", "/usr/share//icons/hicolor/16x16/apps/rapid-photo-downloader.png" },
     {"XSane - Scanning", "xsane", "/usr/share/pixmaps/xsane.xpm" },
     {"gThumb", "gthumb ", "/usr/share//icons/hicolor/16x16/apps/gthumb.png" },
 }

 local menuc8205c7636e728d448c2774e6a4a944b = {
     {"Avahi SSH Server Browser", "/usr/bin/bssh", "/usr/share//icons/gnome/16x16/devices/network-wired.png" },
     {"Avahi VNC Server Browser", "/usr/bin/bvnc", "/usr/share//icons/gnome/16x16/devices/network-wired.png" },
     {"Corebird", "corebird", "/usr/share//icons/hicolor/16x16/apps/corebird.png" },
     {"Dropbox", "dropbox", "/usr/share//icons/hicolor/16x16/apps/dropbox.png" },
     {"ELinks", "xterm -e /usr/bin/elinks ", "/usr/share//icons/gnome/16x16/mimetypes/html.png" },
     {"Empathy", "empathy", "/usr/share//icons/hicolor/16x16/apps/empathy.png" },
     {"Firefox", "firefox ", "/usr/share//icons/hicolor/16x16/apps/firefox.png" },
     {"Firefox - Developer Edition", "/usr/bin/flatpak run --branch=master --arch=x86_64 --command=firefox org.mozilla.FirefoxDevEdition ", "/var/lib/flatpak/exports/share//icons/hicolor/128x128/apps/org.mozilla.FirefoxDevEdition.png" },
     {"Google Chrome", "/usr/bin/google-chrome-stable ", "/usr/share//icons/hicolor/16x16/apps/google-chrome.png" },
     {"Gradio", "gradio", "/usr/share//icons/hicolor/16x16/apps/de.haeckerfelix.gradio.png" },
     {"KDE Connect Monitor", "plasmawindowed org.kde.kdeconnect --statusnotifier", "/usr/share//icons/hicolor/16x16/apps/kdeconnect.png" },
     {"Mumble", "mumble "},
     {"Ricochet IM", "ricochet", "/usr/share//icons/hicolor/48x48/apps/ricochet.png" },
     {"Skype for Linux Alpha", "/usr/bin/skypeforlinux ", "/usr/share//icons/hicolor/16x16/apps/skypeforlinux.png" },
     {"Thunderbird", "thunderbird ", "/usr/share//icons/hicolor/16x16/apps/thunderbird.png" },
     {"Transmission", "transmission-gtk ", "/usr/share//icons/hicolor/16x16/apps/transmission.png" },
     {"Web", "epiphany ", "/usr/share//icons/gnome/16x16/apps/web-browser.png" },
     {"Wireshark (GTK+)", "wireshark-gtk ", "/usr/share//icons/hicolor/16x16/apps/wireshark.png" },
     {"qTox", "qtox ", "/usr/share//icons/hicolor/16x16/apps/qtox.png" },
     {"qutebrowser", "qutebrowser ", "/usr/share//icons/hicolor/16x16/apps/qutebrowser.png" },
 }

 local menudf814135652a5a308fea15bff37ea284 = {
     {"Calendar", "gnome-calendar", "/usr/share//icons/hicolor/16x16/apps/org.gnome.Calendar.png" },
     {"Dictionary", "gnome-dictionary", "/usr/share//icons/gnome/16x16/apps/accessories-dictionary.png" },
     {"Document Viewer", "evince ", "/usr/share//icons/hicolor/16x16/apps/evince.png" },
     {"KOrganizer", "korganizer ", "/usr/share//icons/hicolor/16x16/apps/korganizer.png" },
     {"LibreOffice", "libreoffice ", "/usr/share//icons/hicolor/16x16/apps/libreoffice-startcenter.png" },
     {"LibreOffice Base", "libreoffice --base ", "/usr/share//icons/hicolor/16x16/apps/libreoffice-base.png" },
     {"LibreOffice Calc", "libreoffice --calc ", "/usr/share//icons/hicolor/16x16/apps/libreoffice-calc.png" },
     {"LibreOffice Draw", "libreoffice --draw ", "/usr/share//icons/hicolor/16x16/apps/libreoffice-draw.png" },
     {"LibreOffice Impress", "libreoffice --impress ", "/usr/share//icons/hicolor/16x16/apps/libreoffice-impress.png" },
     {"LibreOffice Math", "libreoffice --math ", "/usr/share//icons/hicolor/16x16/apps/libreoffice-math.png" },
     {"LibreOffice Writer", "libreoffice --writer ", "/usr/share//icons/hicolor/16x16/apps/libreoffice-writer.png" },
     {"Okular", "okular ", "/usr/share//icons/hicolor/16x16/apps/okular.png" },
     {"TeXstudio", "texstudio "},
     {"WordNet", "wnb", "///usr/share/pixmaps/wordnet.png" },
     {"Zathura", "zathura "},
     {"Zotero", "/usr/bin/zotero ", "/usr/share//icons/hicolor/16x16/apps/zotero.png" },
 }

 local menu6311ae17c1ee52b36e68aaf4ad066387 = {
     {"Xcircuit", "xcircuit", "/usr/share//icons/xcircuit.png" },
 }

 local menue6f43c40ab1c07cd29e4e83e4ef6bf85 = {
     {"CMake", "cmake-gui ", "/usr/share//icons/hicolor/32x32/apps/CMakeSetup.png" },
     {"Cuttlefish", "cuttlefish"},
     {"D-Feet", "d-feet", "/usr/share//icons/hicolor/16x16/apps/d-feet.png" },
     {"Data Display Debugger", "ddd", "/usr/share/pixmaps/ddd.xpm" },
     {"FLUID", "fluid ", "/usr/share//icons/hicolor/16x16/apps/fluid.png" },
     {"GHex", "ghex ", "/usr/share//icons/hicolor/16x16/apps/ghex.png" },
     {"GRC", "gnuradio-companion "},
     {"Julia", "xterm -e julia"},
     {"Nemiver", "nemiver", "/usr/share//icons/hicolor/16x16/apps/nemiver.png" },
     {"OpenJDK 1.7.0 Policy Tool", "_BINDIR_/policytool"},
     {"Plasma Look And Feel Explorer", "lookandfeelexplorer", "/usr/share//icons/gnome/16x16/apps/preferences-desktop-theme.png" },
     {"Plasma Theme Explorer", "plasmathemeexplorer", "/usr/share//icons/gnome/16x16/apps/preferences-desktop-theme.png" },
     {"Plasmate", "plasmate"},
     {"Qt Assistant", "assistant", "/usr/share//icons/hicolor/32x32/apps/assistant.png" },
     {"Qt Designer", "designer", "/usr/share//icons/hicolor/128x128/apps/QtProject-designer.png" },
     {"Qt Linguist", "linguist", "/usr/share//icons/hicolor/16x16/apps/linguist.png" },
     {"Qt QDbusViewer ", "qdbusviewer", "/usr/share//icons/hicolor/32x32/apps/qdbusviewer.png" },
     {"Qt4 Assistant ", "assistant-qt4", "/usr/share//icons/hicolor/32x32/apps/assistant-qt4.png" },
     {"Qt4 Designer", "designer-qt4", "/usr/share//icons/hicolor/128x128/apps/designer-qt4.png" },
     {"Qt4 Linguist ", "linguist-qt4", "/usr/share//icons/hicolor/16x16/apps/linguist-qt4.png" },
     {"Qt4 QDbusViewer ", "qdbusviewer-qt4", "/usr/share//icons/hicolor/32x32/apps/qdbusviewer-qt4.png" },
     {"ipython", "xterm -e ipython", "/usr/share/pixmaps/ipython.png" },
 }

 local menu80d754c83abbbd4ef5d150904efcc86c = {
     {"Julia", "xterm -e julia"},
 }

 local menu52dd1c847264a75f400961bfb4d1c849 = {
     {"Brasero", "brasero ", "/usr/share//icons/hicolor/16x16/apps/brasero.png" },
     {"Cheese", "cheese", "/usr/share//icons/hicolor/16x16/apps/org.gnome.Cheese.png" },
     {"Clementine", "clementine ", "/usr/share//icons/hicolor/64x64/apps/clementine.png" },
     {"FFADO Mixer", "ffado-mixer", "/usr/share/pixmaps/ffado.png" },
     {"Music", "gnome-music", "/usr/share//icons/hicolor/16x16/apps/gnome-music.png" },
     {"PulseAudio Volume Control", "pavucontrol", "/usr/share//icons/hicolor/16x16/apps/multimedia-volume-control.png" },
     {"Qt V4L2 test Utility", "qv4l2", "/usr/share//icons/hicolor/16x16/apps/qv4l2.png" },
     {"Sound Recorder", "gnome-sound-recorder", "/usr/share//icons/hicolor/16x16/apps/gnome-sound-recorder.png" },
     {"Spotify", "spotify ", "/usr/share/pixmaps/spotify-client.png" },
     {"guvcview", "guvcview", "///usr/share/pixmaps/guvcview/guvcview.png" },
     {"mpv Media Player", "mpv --player-operation-mode=pseudo-gui -- ", "/usr/share//icons/hicolor/16x16/apps/mpv.png" },
     {"qTox", "qtox ", "/usr/share//icons/hicolor/16x16/apps/qtox.png" },
 }

 local menuee69799670a33f75d45c57d1d1cd0ab3 = {
     {"Avahi Zeroconf Browser", "/usr/bin/avahi-discover", "/usr/share//icons/gnome/16x16/devices/network-wired.png" },
     {"Boxes", "gnome-boxes ", "/usr/share//icons/hicolor/16x16/apps/gnome-boxes.png" },
     {"Color Profile Viewer", "gcm-viewer", "/usr/share//icons/hicolor/16x16/apps/gnome-color-manager.png" },
     {"Configuration Editor", "gconf-editor", "/usr/share//icons/hicolor/16x16/apps/gconf-editor.png" },
     {"Disk Usage Analyzer", "baobab", "/usr/share//icons/hicolor/16x16/apps/baobab.png" },
     {"Dolphin", "dolphin ", "/usr/share//icons/gnome/16x16/apps/system-file-manager.png" },
     {"FSV", "fsv2", "/usr/share/pixmaps/fsv2.xpm" },
     {"GParted", "/usr/bin/gparted_polkit ", "/usr/share//icons/hicolor/16x16/apps/gparted.png" },
     {"Hardware Locality lstopo", "lstopo"},
     {"Htop", "xterm -e htop", "/usr/share/pixmaps/htop.png" },
     {"KSysGuard", "ksysguard ", "/usr/share//icons/gnome/16x16/apps/utilities-system-monitor.png" },
     {"KWalletManager", "kwalletmanager5 ", "/usr/share//icons/hicolor/16x16/apps/kwalletmanager.png" },
     {"Konsole", "konsole", "/usr/share//icons/gnome/16x16/apps/utilities-terminal.png" },
     {"LSHW", "/usr/sbin/gtk-lshw", "///usr/share/lshw/artwork/logo.svg" },
     {"Manage Printing", "/usr/bin/xdg-open http://localhost:631/", "/usr/share//icons/hicolor/16x16/apps/cups.png" },
     {"Pacman Log Viewer", "plv", "/usr/share//icons/hicolor/16x16/apps/plv.png" },
     {"UXTerm", "uxterm", "/usr/share/pixmaps/xterm-color_48x48.xpm" },
     {"Vifm", "xterm -e vifm ", "/usr/share/pixmaps/vifm.png" },
     {"XTerm", "xterm", "/usr/share/pixmaps/xterm-color_48x48.xpm" },
     {"dconf Editor", "dconf-editor", "/usr/share//icons/hicolor/16x16/apps/dconf-editor.png" },
     {"gtk2fontsel", "gtk2fontsel"},
     {"ranger", "xterm -e ranger", "/usr/share//icons/gnome/16x16/apps/utilities-terminal.png" },
     {"st", "st", "/usr/share//icons/gnome/16x16/apps/utilities-terminal.png" },
     {"urxvt", "urxvt", "/usr/share//icons/gnome/16x16/apps/utilities-terminal.png" },
     {"urxvt (client)", "urxvtc", "/usr/share//icons/gnome/16x16/apps/utilities-terminal.png" },
     {"urxvt (tabbed)", "urxvt-tabbed", "/usr/share//icons/gnome/16x16/apps/utilities-terminal.png" },
 }

xdgmenu = {
    {"Accessories", menu98edb85b00d9527ad5acebe451b3fae6},
    {"Education", menude7a22a0c94aa64ba2449e520aa20c99},
    {"Games", menu251bd8143891238ecedc306508e29017},
    {"Graphics", menud334dfcea59127bedfcdbe0a3ee7f494},
    {"Internet", menuc8205c7636e728d448c2774e6a4a944b},
    {"Office", menudf814135652a5a308fea15bff37ea284},
    {"Other", menu6311ae17c1ee52b36e68aaf4ad066387},
    {"Programming", menue6f43c40ab1c07cd29e4e83e4ef6bf85},
    {"Science & Math", menu80d754c83abbbd4ef5d150904efcc86c},
    {"Sound & Video", menu52dd1c847264a75f400961bfb4d1c849},
    {"System Tools", menuee69799670a33f75d45c57d1d1cd0ab3},
}

